quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/smooth_academy
quarkus.datasource.username=smooth
quarkus.datasource.password=smooth_pass

quarkus.hibernate-orm.database.generation=update

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=location,info
quarkus.http.cors.access-control-allow-credentials=true

quarkus.rest.path=/api

%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/smooth_academy
%dev.quarkus.log.level=DEBUG
