quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/smooth_academy
quarkus.datasource.username=smooth
quarkus.datasource.password=smooth_pass

quarkus.hibernate-orm.database.generation=update

quarkus.rest.path=/api

%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/smooth_academy
%dev.quarkus.log.level=DEBUG
